name: build
on: 
  push:
    branches:
      - 'current'
  pull_request:
    branches:
      - 'current'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Maven
      run: mvn --no-transfer-progress -B package
